// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AsmDude2
{
    internal sealed partial class Vsix
    {
        public const string Id = "4f792145-bd77-482d-bd0e-fcc7ac281c8d";
        public const string Name = "AsmDude2";
        public const string Description = @"Syntax highlighting and code assistance for assembly source code (.asm, .cod, .inc, .s) and the Disassembly Window ";
        public const string Language = "en-US";
        public const string Version = "2.0.0.0";
        public const string Author = "Henk-Jan Lebbink";
        public const string Tags = "Assembly, Assembler, ASM, Syntax Highlighting, Code Completion, Disassembly Window, Code Analysis, x86_64, SSE, AVX, AVX2, AVX512";
    }
}
