//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmDude {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color SyntaxHighlighting_Opcode {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Opcode"]));
            }
            set {
                this["SyntaxHighlighting_Opcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color SyntaxHighlighting_Register {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Register"]));
            }
            set {
                this["SyntaxHighlighting_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color SyntaxHighlighting_Remark {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Remark"]));
            }
            set {
                this["SyntaxHighlighting_Remark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.Drawing.Color SyntaxHighlighting_Directive {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Directive"]));
            }
            set {
                this["SyntaxHighlighting_Directive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color SyntaxHighlighting_Jump {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Jump"]));
            }
            set {
                this["SyntaxHighlighting_Jump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color SyntaxHighlighting_Label {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Label"]));
            }
            set {
                this["SyntaxHighlighting_Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chocolate")]
        public global::System.Drawing.Color SyntaxHighlighting_Constant {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Constant"]));
            }
            set {
                this["SyntaxHighlighting_Constant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color SyntaxHighlighting_Misc {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Misc"]));
            }
            set {
                this["SyntaxHighlighting_Misc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyntaxHighlighting_On {
            get {
                return ((bool)(this["SyntaxHighlighting_On"]));
            }
            set {
                this["SyntaxHighlighting_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeFolding_On {
            get {
                return ((bool)(this["CodeFolding_On"]));
            }
            set {
                this["CodeFolding_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#region")]
        public string CodeFolding_BeginTag {
            get {
                return ((string)(this["CodeFolding_BeginTag"]));
            }
            set {
                this["CodeFolding_BeginTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#endregion")]
        public string CodeFolding_EndTag {
            get {
                return ((string)(this["CodeFolding_EndTag"]));
            }
            set {
                this["CodeFolding_EndTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_On {
            get {
                return ((bool)(this["CodeCompletion_On"]));
            }
            set {
                this["CodeCompletion_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/HJLebbink/asm-dude/wiki/")]
        public string AsmDoc_Url {
            get {
                return ((string)(this["AsmDoc_Url"]));
            }
            set {
                this["AsmDoc_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsmDoc_On {
            get {
                return ((bool)(this["AsmDoc_On"]));
            }
            set {
                this["AsmDoc_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeywordHighlighting_BackgroundColor_On {
            get {
                return ((bool)(this["KeywordHighlighting_BackgroundColor_On"]));
            }
            set {
                this["KeywordHighlighting_BackgroundColor_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color KeywordHighlighting_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["KeywordHighlighting_BackgroundColor"]));
            }
            set {
                this["KeywordHighlighting_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeFolding_IsDefaultCollapsed {
            get {
                return ((bool)(this["CodeFolding_IsDefaultCollapsed"]));
            }
            set {
                this["CodeFolding_IsDefaultCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useAssemblerMasm {
            get {
                return ((bool)(this["useAssemblerMasm"]));
            }
            set {
                this["useAssemblerMasm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useAssemblerNasm {
            get {
                return ((bool)(this["useAssemblerNasm"]));
            }
            set {
                this["useAssemblerNasm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Show_Undefined_Labels {
            get {
                return ((bool)(this["IntelliSense_Show_Undefined_Labels"]));
            }
            set {
                this["IntelliSense_Show_Undefined_Labels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Show_Clashing_Labels {
            get {
                return ((bool)(this["IntelliSense_Show_Clashing_Labels"]));
            }
            set {
                this["IntelliSense_Show_Clashing_Labels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Decorate_Undefined_Labels {
            get {
                return ((bool)(this["IntelliSense_Decorate_Undefined_Labels"]));
            }
            set {
                this["IntelliSense_Decorate_Undefined_Labels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Decorate_Clashing_Labels {
            get {
                return ((bool)(this["IntelliSense_Decorate_Clashing_Labels"]));
            }
            set {
                this["IntelliSense_Decorate_Clashing_Labels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_8086 {
            get {
                return ((bool)(this["ARCH_8086"]));
            }
            set {
                this["ARCH_8086"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_186 {
            get {
                return ((bool)(this["ARCH_186"]));
            }
            set {
                this["ARCH_186"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_286 {
            get {
                return ((bool)(this["ARCH_286"]));
            }
            set {
                this["ARCH_286"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_386 {
            get {
                return ((bool)(this["ARCH_386"]));
            }
            set {
                this["ARCH_386"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_486 {
            get {
                return ((bool)(this["ARCH_486"]));
            }
            set {
                this["ARCH_486"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_MMX {
            get {
                return ((bool)(this["ARCH_MMX"]));
            }
            set {
                this["ARCH_MMX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE {
            get {
                return ((bool)(this["ARCH_SSE"]));
            }
            set {
                this["ARCH_SSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE2 {
            get {
                return ((bool)(this["ARCH_SSE2"]));
            }
            set {
                this["ARCH_SSE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE3 {
            get {
                return ((bool)(this["ARCH_SSE3"]));
            }
            set {
                this["ARCH_SSE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSSE3 {
            get {
                return ((bool)(this["ARCH_SSSE3"]));
            }
            set {
                this["ARCH_SSSE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE4_1 {
            get {
                return ((bool)(this["ARCH_SSE4_1"]));
            }
            set {
                this["ARCH_SSE4_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE4_2 {
            get {
                return ((bool)(this["ARCH_SSE4_2"]));
            }
            set {
                this["ARCH_SSE4_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SSE4A {
            get {
                return ((bool)(this["ARCH_SSE4A"]));
            }
            set {
                this["ARCH_SSE4A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SSE5 {
            get {
                return ((bool)(this["ARCH_SSE5"]));
            }
            set {
                this["ARCH_SSE5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX {
            get {
                return ((bool)(this["ARCH_AVX"]));
            }
            set {
                this["ARCH_AVX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX2 {
            get {
                return ((bool)(this["ARCH_AVX2"]));
            }
            set {
                this["ARCH_AVX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512_VL {
            get {
                return ((bool)(this["ARCH_AVX512_VL"]));
            }
            set {
                this["ARCH_AVX512_VL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_PF {
            get {
                return ((bool)(this["ARCH_AVX512_PF"]));
            }
            set {
                this["ARCH_AVX512_PF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512_DQ {
            get {
                return ((bool)(this["ARCH_AVX512_DQ"]));
            }
            set {
                this["ARCH_AVX512_DQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512_BW {
            get {
                return ((bool)(this["ARCH_AVX512_BW"]));
            }
            set {
                this["ARCH_AVX512_BW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_ER {
            get {
                return ((bool)(this["ARCH_AVX512_ER"]));
            }
            set {
                this["ARCH_AVX512_ER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512_F {
            get {
                return ((bool)(this["ARCH_AVX512_F"]));
            }
            set {
                this["ARCH_AVX512_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512_CD {
            get {
                return ((bool)(this["ARCH_AVX512_CD"]));
            }
            set {
                this["ARCH_AVX512_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_X64 {
            get {
                return ((bool)(this["ARCH_X64"]));
            }
            set {
                this["ARCH_X64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BMI1 {
            get {
                return ((bool)(this["ARCH_BMI1"]));
            }
            set {
                this["ARCH_BMI1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BMI2 {
            get {
                return ((bool)(this["ARCH_BMI2"]));
            }
            set {
                this["ARCH_BMI2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_P6 {
            get {
                return ((bool)(this["ARCH_P6"]));
            }
            set {
                this["ARCH_P6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_IA64 {
            get {
                return ((bool)(this["ARCH_IA64"]));
            }
            set {
                this["ARCH_IA64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FMA {
            get {
                return ((bool)(this["ARCH_FMA"]));
            }
            set {
                this["ARCH_FMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_TBM {
            get {
                return ((bool)(this["ARCH_TBM"]));
            }
            set {
                this["ARCH_TBM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AMD {
            get {
                return ((bool)(this["ARCH_AMD"]));
            }
            set {
                this["ARCH_AMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_PENT {
            get {
                return ((bool)(this["ARCH_PENT"]));
            }
            set {
                this["ARCH_PENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_3DNOW {
            get {
                return ((bool)(this["ARCH_3DNOW"]));
            }
            set {
                this["ARCH_3DNOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_CYRIX {
            get {
                return ((bool)(this["ARCH_CYRIX"]));
            }
            set {
                this["ARCH_CYRIX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_CYRIXM {
            get {
                return ((bool)(this["ARCH_CYRIXM"]));
            }
            set {
                this["ARCH_CYRIXM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_VMX {
            get {
                return ((bool)(this["ARCH_VMX"]));
            }
            set {
                this["ARCH_VMX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RTM {
            get {
                return ((bool)(this["ARCH_RTM"]));
            }
            set {
                this["ARCH_RTM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_MPX {
            get {
                return ((bool)(this["ARCH_MPX"]));
            }
            set {
                this["ARCH_MPX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SHA {
            get {
                return ((bool)(this["ARCH_SHA"]));
            }
            set {
                this["ARCH_SHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BND {
            get {
                return ((bool)(this["ARCH_BND"]));
            }
            set {
                this["ARCH_BND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SignatureHelp_On {
            get {
                return ((bool)(this["SignatureHelp_On"]));
            }
            set {
                this["SignatureHelp_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_ADX {
            get {
                return ((bool)(this["ARCH_ADX"]));
            }
            set {
                this["ARCH_ADX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_F16C {
            get {
                return ((bool)(this["ARCH_F16C"]));
            }
            set {
                this["ARCH_F16C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_FSGSBASE {
            get {
                return ((bool)(this["ARCH_FSGSBASE"]));
            }
            set {
                this["ARCH_FSGSBASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_HLE {
            get {
                return ((bool)(this["ARCH_HLE"]));
            }
            set {
                this["ARCH_HLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_INVPCID {
            get {
                return ((bool)(this["ARCH_INVPCID"]));
            }
            set {
                this["ARCH_INVPCID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_PCLMULQDQ {
            get {
                return ((bool)(this["ARCH_PCLMULQDQ"]));
            }
            set {
                this["ARCH_PCLMULQDQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_LZCNT {
            get {
                return ((bool)(this["ARCH_LZCNT"]));
            }
            set {
                this["ARCH_LZCNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_PREFETCHWT1 {
            get {
                return ((bool)(this["ARCH_PREFETCHWT1"]));
            }
            set {
                this["ARCH_PREFETCHWT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDPID {
            get {
                return ((bool)(this["ARCH_RDPID"]));
            }
            set {
                this["ARCH_RDPID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDRAND {
            get {
                return ((bool)(this["ARCH_RDRAND"]));
            }
            set {
                this["ARCH_RDRAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDSEED {
            get {
                return ((bool)(this["ARCH_RDSEED"]));
            }
            set {
                this["ARCH_RDSEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_XSAVEOPT {
            get {
                return ((bool)(this["ARCH_XSAVEOPT"]));
            }
            set {
                this["ARCH_XSAVEOPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_UNDOC {
            get {
                return ((bool)(this["ARCH_UNDOC"]));
            }
            set {
                this["ARCH_UNDOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AES {
            get {
                return ((bool)(this["ARCH_AES"]));
            }
            set {
                this["ARCH_AES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Show_Undefined_Includes {
            get {
                return ((bool)(this["IntelliSense_Show_Undefined_Includes"]));
            }
            set {
                this["IntelliSense_Show_Undefined_Includes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color KeywordHighlighting_BorderColor {
            get {
                return ((global::System.Drawing.Color)(this["KeywordHighlighting_BorderColor"]));
            }
            set {
                this["KeywordHighlighting_BorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_SandyBridge_On {
            get {
                return ((bool)(this["PerformanceInfo_SandyBridge_On"]));
            }
            set {
                this["PerformanceInfo_SandyBridge_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_IvyBridge_On {
            get {
                return ((bool)(this["PerformanceInfo_IvyBridge_On"]));
            }
            set {
                this["PerformanceInfo_IvyBridge_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_Haswell_On {
            get {
                return ((bool)(this["PerformanceInfo_Haswell_On"]));
            }
            set {
                this["PerformanceInfo_Haswell_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_Broadwell_On {
            get {
                return ((bool)(this["PerformanceInfo_Broadwell_On"]));
            }
            set {
                this["PerformanceInfo_Broadwell_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_Skylake_On {
            get {
                return ((bool)(this["PerformanceInfo_Skylake_On"]));
            }
            set {
                this["PerformanceInfo_Skylake_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_KnightsLanding_On {
            get {
                return ((bool)(this["PerformanceInfo_KnightsLanding_On"]));
            }
            set {
                this["PerformanceInfo_KnightsLanding_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeywordHighlighting_BorderColor_On {
            get {
                return ((bool)(this["KeywordHighlighting_BorderColor_On"]));
            }
            set {
                this["KeywordHighlighting_BorderColor_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_On {
            get {
                return ((bool)(this["AsmSim_On"]));
            }
            set {
                this["AsmSim_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Show_Syntax_Errors {
            get {
                return ((bool)(this["AsmSim_Show_Syntax_Errors"]));
            }
            set {
                this["AsmSim_Show_Syntax_Errors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Decorate_Syntax_Errors {
            get {
                return ((bool)(this["AsmSim_Decorate_Syntax_Errors"]));
            }
            set {
                this["AsmSim_Decorate_Syntax_Errors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Show_Usage_Of_Undefined {
            get {
                return ((bool)(this["AsmSim_Show_Usage_Of_Undefined"]));
            }
            set {
                this["AsmSim_Show_Usage_Of_Undefined"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Decorate_Usage_Of_Undefined {
            get {
                return ((bool)(this["AsmSim_Decorate_Usage_Of_Undefined"]));
            }
            set {
                this["AsmSim_Decorate_Usage_Of_Undefined"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Decorate_Registers {
            get {
                return ((bool)(this["AsmSim_Decorate_Registers"]));
            }
            set {
                this["AsmSim_Decorate_Registers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Show_Register_In_Code_Completion {
            get {
                return ((bool)(this["AsmSim_Show_Register_In_Code_Completion"]));
            }
            set {
                this["AsmSim_Show_Register_In_Code_Completion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Decorate_Unimplemented {
            get {
                return ((bool)(this["AsmSim_Decorate_Unimplemented"]));
            }
            set {
                this["AsmSim_Decorate_Unimplemented"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Decorate_Undefined_Includes {
            get {
                return ((bool)(this["IntelliSense_Decorate_Undefined_Includes"]));
            }
            set {
                this["IntelliSense_Decorate_Undefined_Includes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_IFMA {
            get {
                return ((bool)(this["ARCH_AVX512_IFMA"]));
            }
            set {
                this["ARCH_AVX512_IFMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VBMI {
            get {
                return ((bool)(this["ARCH_AVX512_VBMI"]));
            }
            set {
                this["ARCH_AVX512_VBMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VPOPCNTDQ {
            get {
                return ((bool)(this["ARCH_AVX512_VPOPCNTDQ"]));
            }
            set {
                this["ARCH_AVX512_VPOPCNTDQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_4VNNIW {
            get {
                return ((bool)(this["ARCH_AVX512_4VNNIW"]));
            }
            set {
                this["ARCH_AVX512_4VNNIW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_4FMAPS {
            get {
                return ((bool)(this["ARCH_AVX512_4FMAPS"]));
            }
            set {
                this["ARCH_AVX512_4FMAPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsmSim_64_Bits {
            get {
                return ((bool)(this["AsmSim_64_Bits"]));
            }
            set {
                this["AsmSim_64_Bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color SyntaxHighlighting_Userdefined1 {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Userdefined1"]));
            }
            set {
                this["SyntaxHighlighting_Userdefined1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color SyntaxHighlighting_Userdefined2 {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Userdefined2"]));
            }
            set {
                this["SyntaxHighlighting_Userdefined2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color SyntaxHighlighting_Userdefined3 {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Userdefined3"]));
            }
            set {
                this["SyntaxHighlighting_Userdefined3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int AsmSim_Z3_Timeout_MS {
            get {
                return ((int)(this["AsmSim_Z3_Timeout_MS"]));
            }
            set {
                this["AsmSim_Z3_Timeout_MS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Show_Redundant_Instructions {
            get {
                return ((bool)(this["AsmSim_Show_Redundant_Instructions"]));
            }
            set {
                this["AsmSim_Show_Redundant_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Decorate_Redundant_Instructions {
            get {
                return ((bool)(this["AsmSim_Decorate_Redundant_Instructions"]));
            }
            set {
                this["AsmSim_Decorate_Redundant_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyntaxHighlighting_Opcode_Italic {
            get {
                return ((bool)(this["SyntaxHighlighting_Opcode_Italic"]));
            }
            set {
                this["SyntaxHighlighting_Opcode_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyntaxHighlighting_Register_Italic {
            get {
                return ((bool)(this["SyntaxHighlighting_Register_Italic"]));
            }
            set {
                this["SyntaxHighlighting_Register_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyntaxHighlighting_Remark_Italic {
            get {
                return ((bool)(this["SyntaxHighlighting_Remark_Italic"]));
            }
            set {
                this["SyntaxHighlighting_Remark_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyntaxHighlighting_Directive_Italic {
            get {
                return ((bool)(this["SyntaxHighlighting_Directive_Italic"]));
            }
            set {
                this["SyntaxHighlighting_Directive_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyntaxHighlighting_Constant_Italic {
            get {
                return ((bool)(this["SyntaxHighlighting_Constant_Italic"]));
            }
            set {
                this["SyntaxHighlighting_Constant_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyntaxHighlighting_Jump_Italic {
            get {
                return ((bool)(this["SyntaxHighlighting_Jump_Italic"]));
            }
            set {
                this["SyntaxHighlighting_Jump_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyntaxHighlighting_Label_Italic {
            get {
                return ((bool)(this["SyntaxHighlighting_Label_Italic"]));
            }
            set {
                this["SyntaxHighlighting_Label_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyntaxHighlighting_Misc_Italic {
            get {
                return ((bool)(this["SyntaxHighlighting_Misc_Italic"]));
            }
            set {
                this["SyntaxHighlighting_Misc_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyntaxHighlighting_Userdefined1_Italic {
            get {
                return ((bool)(this["SyntaxHighlighting_Userdefined1_Italic"]));
            }
            set {
                this["SyntaxHighlighting_Userdefined1_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyntaxHighlighting_Userdefined2_Italic {
            get {
                return ((bool)(this["SyntaxHighlighting_Userdefined2_Italic"]));
            }
            set {
                this["SyntaxHighlighting_Userdefined2_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyntaxHighlighting_Userdefined3_Italic {
            get {
                return ((bool)(this["SyntaxHighlighting_Userdefined3_Italic"]));
            }
            set {
                this["SyntaxHighlighting_Userdefined3_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Label_Analysis_On {
            get {
                return ((bool)(this["IntelliSense_Label_Analysis_On"]));
            }
            set {
                this["IntelliSense_Label_Analysis_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useAssemblerNasm_Att {
            get {
                return ((bool)(this["useAssemblerNasm_Att"]));
            }
            set {
                this["useAssemblerNasm_Att"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AsmSim_Number_Of_Threads {
            get {
                return ((int)(this["AsmSim_Number_Of_Threads"]));
            }
            set {
                this["AsmSim_Number_Of_Threads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Show_Unreachable_Instructions {
            get {
                return ((bool)(this["AsmSim_Show_Unreachable_Instructions"]));
            }
            set {
                this["AsmSim_Show_Unreachable_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Decorate_Unreachable_Instructions {
            get {
                return ((bool)(this["AsmSim_Decorate_Unreachable_Instructions"]));
            }
            set {
                this["AsmSim_Decorate_Unreachable_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#pragma assume")]
        public string AsmSim_Pragma_Assume {
            get {
                return ((string)(this["AsmSim_Pragma_Assume"]));
            }
            set {
                this["AsmSim_Pragma_Assume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsmSim_Show_Register_In_Instruction_Tooltip {
            get {
                return ((bool)(this["AsmSim_Show_Register_In_Instruction_Tooltip"]));
            }
            set {
                this["AsmSim_Show_Register_In_Instruction_Tooltip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsmSim_Show_Register_In_Register_Tooltip {
            get {
                return ((bool)(this["AsmSim_Show_Register_In_Register_Tooltip"]));
            }
            set {
                this["AsmSim_Show_Register_In_Register_Tooltip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HEX")]
        public string AsmSim_Show_Register_In_Code_Completion_Numeration {
            get {
                return ((string)(this["AsmSim_Show_Register_In_Code_Completion_Numeration"]));
            }
            set {
                this["AsmSim_Show_Register_In_Code_Completion_Numeration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HEX")]
        public string AsmSim_Show_Register_In_Instruction_Tooltip_Numeration {
            get {
                return ((string)(this["AsmSim_Show_Register_In_Instruction_Tooltip_Numeration"]));
            }
            set {
                this["AsmSim_Show_Register_In_Instruction_Tooltip_Numeration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HEX")]
        public string AsmSim_Show_Register_In_Register_Tooltip_Numeration {
            get {
                return ((string)(this["AsmSim_Show_Register_In_Register_Tooltip_Numeration"]));
            }
            set {
                this["AsmSim_Show_Register_In_Register_Tooltip_Numeration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VBMI2 {
            get {
                return ((bool)(this["ARCH_AVX512_VBMI2"]));
            }
            set {
                this["ARCH_AVX512_VBMI2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VNNI {
            get {
                return ((bool)(this["ARCH_AVX512_VNNI"]));
            }
            set {
                this["ARCH_AVX512_VNNI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_BITALG {
            get {
                return ((bool)(this["ARCH_AVX512_BITALG"]));
            }
            set {
                this["ARCH_AVX512_BITALG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_GFNI {
            get {
                return ((bool)(this["ARCH_AVX512_GFNI"]));
            }
            set {
                this["ARCH_AVX512_GFNI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VAES {
            get {
                return ((bool)(this["ARCH_AVX512_VAES"]));
            }
            set {
                this["ARCH_AVX512_VAES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VPCLMULQDQ {
            get {
                return ((bool)(this["ARCH_AVX512_VPCLMULQDQ"]));
            }
            set {
                this["ARCH_AVX512_VPCLMULQDQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SMX {
            get {
                return ((bool)(this["ARCH_SMX"]));
            }
            set {
                this["ARCH_SMX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SGX1 {
            get {
                return ((bool)(this["ARCH_SGX1"]));
            }
            set {
                this["ARCH_SGX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SGX2 {
            get {
                return ((bool)(this["ARCH_SGX2"]));
            }
            set {
                this["ARCH_SGX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PerformanceInfo_SkylakeX_On {
            get {
                return ((bool)(this["PerformanceInfo_SkylakeX_On"]));
            }
            set {
                this["PerformanceInfo_SkylakeX_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_IsDefaultCollapsed {
            get {
                return ((bool)(this["PerformanceInfo_IsDefaultCollapsed"]));
            }
            set {
                this["PerformanceInfo_IsDefaultCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PerformanceInfo_On {
            get {
                return ((bool)(this["PerformanceInfo_On"]));
            }
            set {
                this["PerformanceInfo_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_CLDEMOTE {
            get {
                return ((bool)(this["ARCH_CLDEMOTE"]));
            }
            set {
                this["ARCH_CLDEMOTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_MOVDIR64B {
            get {
                return ((bool)(this["ARCH_MOVDIR64B"]));
            }
            set {
                this["ARCH_MOVDIR64B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_MOVDIRI {
            get {
                return ((bool)(this["ARCH_MOVDIRI"]));
            }
            set {
                this["ARCH_MOVDIRI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_PCONFIG {
            get {
                return ((bool)(this["ARCH_PCONFIG"]));
            }
            set {
                this["ARCH_PCONFIG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_WAITPKG {
            get {
                return ((bool)(this["ARCH_WAITPKG"]));
            }
            set {
                this["ARCH_WAITPKG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_PRFCHW {
            get {
                return ((bool)(this["ARCH_PRFCHW"]));
            }
            set {
                this["ARCH_PRFCHW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_BF16 {
            get {
                return ((bool)(this["ARCH_AVX512_BF16"]));
            }
            set {
                this["ARCH_AVX512_BF16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VP2INTERSECT {
            get {
                return ((bool)(this["ARCH_AVX512_VP2INTERSECT"]));
            }
            set {
                this["ARCH_AVX512_VP2INTERSECT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_ENQCMD {
            get {
                return ((bool)(this["ARCH_ENQCMD"]));
            }
            set {
                this["ARCH_ENQCMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useAssemblerDisassemblyMasm {
            get {
                return ((bool)(this["useAssemblerDisassemblyMasm"]));
            }
            set {
                this["useAssemblerDisassemblyMasm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useAssemblerDisassemblyNasm_Att {
            get {
                return ((bool)(this["useAssemblerDisassemblyNasm_Att"]));
            }
            set {
                this["useAssemblerDisassemblyNasm_Att"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useAssemblerDisassemblyAutoDetect {
            get {
                return ((bool)(this["useAssemblerDisassemblyAutoDetect"]));
            }
            set {
                this["useAssemblerDisassemblyAutoDetect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useAssemblerAutoDetect {
            get {
                return ((bool)(this["useAssemblerAutoDetect"]));
            }
            set {
                this["useAssemblerAutoDetect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public int Global_MaxFileLines {
            get {
                return ((int)(this["Global_MaxFileLines"]));
            }
            set {
                this["Global_MaxFileLines"] = value;
            }
        }
    }
}
