//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmDude.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color SyntaxHighlighting_Opcode {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Opcode"]));
            }
            set {
                this["SyntaxHighlighting_Opcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color SyntaxHighlighting_Register {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Register"]));
            }
            set {
                this["SyntaxHighlighting_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color SyntaxHighlighting_Remark {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Remark"]));
            }
            set {
                this["SyntaxHighlighting_Remark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.Drawing.Color SyntaxHighlighting_Directive {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Directive"]));
            }
            set {
                this["SyntaxHighlighting_Directive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color SyntaxHighlighting_Jump {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Jump"]));
            }
            set {
                this["SyntaxHighlighting_Jump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color SyntaxHighlighting_Label {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Label"]));
            }
            set {
                this["SyntaxHighlighting_Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chocolate")]
        public global::System.Drawing.Color SyntaxHighlighting_Constant {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Constant"]));
            }
            set {
                this["SyntaxHighlighting_Constant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color SyntaxHighlighting_Misc {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Misc"]));
            }
            set {
                this["SyntaxHighlighting_Misc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyntaxHighlighting_On {
            get {
                return ((bool)(this["SyntaxHighlighting_On"]));
            }
            set {
                this["SyntaxHighlighting_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeFolding_On {
            get {
                return ((bool)(this["CodeFolding_On"]));
            }
            set {
                this["CodeFolding_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#region")]
        public string CodeFolding_BeginTag {
            get {
                return ((string)(this["CodeFolding_BeginTag"]));
            }
            set {
                this["CodeFolding_BeginTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#endregion")]
        public string CodeFolding_EndTag {
            get {
                return ((string)(this["CodeFolding_EndTag"]));
            }
            set {
                this["CodeFolding_EndTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_On {
            get {
                return ((bool)(this["CodeCompletion_On"]));
            }
            set {
                this["CodeCompletion_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_x86 {
            get {
                return ((bool)(this["CodeCompletion_x86"]));
            }
            set {
                this["CodeCompletion_x86"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_sse {
            get {
                return ((bool)(this["CodeCompletion_sse"]));
            }
            set {
                this["CodeCompletion_sse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_sse2 {
            get {
                return ((bool)(this["CodeCompletion_sse2"]));
            }
            set {
                this["CodeCompletion_sse2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_sse3 {
            get {
                return ((bool)(this["CodeCompletion_sse3"]));
            }
            set {
                this["CodeCompletion_sse3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_ssse3 {
            get {
                return ((bool)(this["CodeCompletion_ssse3"]));
            }
            set {
                this["CodeCompletion_ssse3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_sse41 {
            get {
                return ((bool)(this["CodeCompletion_sse41"]));
            }
            set {
                this["CodeCompletion_sse41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_sse42 {
            get {
                return ((bool)(this["CodeCompletion_sse42"]));
            }
            set {
                this["CodeCompletion_sse42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_avx {
            get {
                return ((bool)(this["CodeCompletion_avx"]));
            }
            set {
                this["CodeCompletion_avx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_avx2 {
            get {
                return ((bool)(this["CodeCompletion_avx2"]));
            }
            set {
                this["CodeCompletion_avx2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CodeCompletion_knc {
            get {
                return ((bool)(this["CodeCompletion_knc"]));
            }
            set {
                this["CodeCompletion_knc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CodeCompletion_mmx {
            get {
                return ((bool)(this["CodeCompletion_mmx"]));
            }
            set {
                this["CodeCompletion_mmx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_i686 {
            get {
                return ((bool)(this["CodeCompletion_i686"]));
            }
            set {
                this["CodeCompletion_i686"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.felixcloutier.com/x86/")]
        public string AsmDoc_url {
            get {
                return ((string)(this["AsmDoc_url"]));
            }
            set {
                this["AsmDoc_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsmDoc_On {
            get {
                return ((bool)(this["AsmDoc_On"]));
            }
            set {
                this["AsmDoc_On"] = value;
            }
        }
    }
}
