//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmDude {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color SyntaxHighlighting_Opcode {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Opcode"]));
            }
            set {
                this["SyntaxHighlighting_Opcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color SyntaxHighlighting_Register {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Register"]));
            }
            set {
                this["SyntaxHighlighting_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color SyntaxHighlighting_Remark {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Remark"]));
            }
            set {
                this["SyntaxHighlighting_Remark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.Drawing.Color SyntaxHighlighting_Directive {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Directive"]));
            }
            set {
                this["SyntaxHighlighting_Directive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color SyntaxHighlighting_Jump {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Jump"]));
            }
            set {
                this["SyntaxHighlighting_Jump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color SyntaxHighlighting_Label {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Label"]));
            }
            set {
                this["SyntaxHighlighting_Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chocolate")]
        public global::System.Drawing.Color SyntaxHighlighting_Constant {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Constant"]));
            }
            set {
                this["SyntaxHighlighting_Constant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color SyntaxHighlighting_Misc {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Misc"]));
            }
            set {
                this["SyntaxHighlighting_Misc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyntaxHighlighting_On {
            get {
                return ((bool)(this["SyntaxHighlighting_On"]));
            }
            set {
                this["SyntaxHighlighting_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeFolding_On {
            get {
                return ((bool)(this["CodeFolding_On"]));
            }
            set {
                this["CodeFolding_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#region")]
        public string CodeFolding_BeginTag {
            get {
                return ((string)(this["CodeFolding_BeginTag"]));
            }
            set {
                this["CodeFolding_BeginTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#endregion")]
        public string CodeFolding_EndTag {
            get {
                return ((string)(this["CodeFolding_EndTag"]));
            }
            set {
                this["CodeFolding_EndTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_On {
            get {
                return ((bool)(this["CodeCompletion_On"]));
            }
            set {
                this["CodeCompletion_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hjlebbink.github.io/x86doc/html/")]
        public string AsmDoc_url {
            get {
                return ((string)(this["AsmDoc_url"]));
            }
            set {
                this["AsmDoc_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsmDoc_On {
            get {
                return ((bool)(this["AsmDoc_On"]));
            }
            set {
                this["AsmDoc_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeywordHighlighting_BackgroundColor_On {
            get {
                return ((bool)(this["KeywordHighlighting_BackgroundColor_On"]));
            }
            set {
                this["KeywordHighlighting_BackgroundColor_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color KeywordHighlighting_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["KeywordHighlighting_BackgroundColor"]));
            }
            set {
                this["KeywordHighlighting_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeFolding_IsDefaultCollapsed {
            get {
                return ((bool)(this["CodeFolding_IsDefaultCollapsed"]));
            }
            set {
                this["CodeFolding_IsDefaultCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useAssemblerMasm {
            get {
                return ((bool)(this["useAssemblerMasm"]));
            }
            set {
                this["useAssemblerMasm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useAssemblerNasm {
            get {
                return ((bool)(this["useAssemblerNasm"]));
            }
            set {
                this["useAssemblerNasm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Show_UndefinedLabels {
            get {
                return ((bool)(this["IntelliSense_Show_UndefinedLabels"]));
            }
            set {
                this["IntelliSense_Show_UndefinedLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Show_ClashingLabels {
            get {
                return ((bool)(this["IntelliSense_Show_ClashingLabels"]));
            }
            set {
                this["IntelliSense_Show_ClashingLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Decorate_UndefinedLabels {
            get {
                return ((bool)(this["IntelliSense_Decorate_UndefinedLabels"]));
            }
            set {
                this["IntelliSense_Decorate_UndefinedLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Decorate_ClashingLabels {
            get {
                return ((bool)(this["IntelliSense_Decorate_ClashingLabels"]));
            }
            set {
                this["IntelliSense_Decorate_ClashingLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_8086 {
            get {
                return ((bool)(this["ARCH_8086"]));
            }
            set {
                this["ARCH_8086"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_186 {
            get {
                return ((bool)(this["ARCH_186"]));
            }
            set {
                this["ARCH_186"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_286 {
            get {
                return ((bool)(this["ARCH_286"]));
            }
            set {
                this["ARCH_286"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_386 {
            get {
                return ((bool)(this["ARCH_386"]));
            }
            set {
                this["ARCH_386"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_486 {
            get {
                return ((bool)(this["ARCH_486"]));
            }
            set {
                this["ARCH_486"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_MMX {
            get {
                return ((bool)(this["ARCH_MMX"]));
            }
            set {
                this["ARCH_MMX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE {
            get {
                return ((bool)(this["ARCH_SSE"]));
            }
            set {
                this["ARCH_SSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE2 {
            get {
                return ((bool)(this["ARCH_SSE2"]));
            }
            set {
                this["ARCH_SSE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE3 {
            get {
                return ((bool)(this["ARCH_SSE3"]));
            }
            set {
                this["ARCH_SSE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSSE3 {
            get {
                return ((bool)(this["ARCH_SSSE3"]));
            }
            set {
                this["ARCH_SSSE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE41 {
            get {
                return ((bool)(this["ARCH_SSE41"]));
            }
            set {
                this["ARCH_SSE41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE42 {
            get {
                return ((bool)(this["ARCH_SSE42"]));
            }
            set {
                this["ARCH_SSE42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SSE4A {
            get {
                return ((bool)(this["ARCH_SSE4A"]));
            }
            set {
                this["ARCH_SSE4A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SSE5 {
            get {
                return ((bool)(this["ARCH_SSE5"]));
            }
            set {
                this["ARCH_SSE5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX {
            get {
                return ((bool)(this["ARCH_AVX"]));
            }
            set {
                this["ARCH_AVX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX2 {
            get {
                return ((bool)(this["ARCH_AVX2"]));
            }
            set {
                this["ARCH_AVX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512VL {
            get {
                return ((bool)(this["ARCH_AVX512VL"]));
            }
            set {
                this["ARCH_AVX512VL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512PF {
            get {
                return ((bool)(this["ARCH_AVX512PF"]));
            }
            set {
                this["ARCH_AVX512PF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512DQ {
            get {
                return ((bool)(this["ARCH_AVX512DQ"]));
            }
            set {
                this["ARCH_AVX512DQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512BW {
            get {
                return ((bool)(this["ARCH_AVX512BW"]));
            }
            set {
                this["ARCH_AVX512BW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512ER {
            get {
                return ((bool)(this["ARCH_AVX512ER"]));
            }
            set {
                this["ARCH_AVX512ER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512F {
            get {
                return ((bool)(this["ARCH_AVX512F"]));
            }
            set {
                this["ARCH_AVX512F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512CD {
            get {
                return ((bool)(this["ARCH_AVX512CD"]));
            }
            set {
                this["ARCH_AVX512CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_X64 {
            get {
                return ((bool)(this["ARCH_X64"]));
            }
            set {
                this["ARCH_X64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BMI1 {
            get {
                return ((bool)(this["ARCH_BMI1"]));
            }
            set {
                this["ARCH_BMI1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BMI2 {
            get {
                return ((bool)(this["ARCH_BMI2"]));
            }
            set {
                this["ARCH_BMI2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_P6 {
            get {
                return ((bool)(this["ARCH_P6"]));
            }
            set {
                this["ARCH_P6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_IA64 {
            get {
                return ((bool)(this["ARCH_IA64"]));
            }
            set {
                this["ARCH_IA64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FMA {
            get {
                return ((bool)(this["ARCH_FMA"]));
            }
            set {
                this["ARCH_FMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_TBM {
            get {
                return ((bool)(this["ARCH_TBM"]));
            }
            set {
                this["ARCH_TBM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AMD {
            get {
                return ((bool)(this["ARCH_AMD"]));
            }
            set {
                this["ARCH_AMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_PENT {
            get {
                return ((bool)(this["ARCH_PENT"]));
            }
            set {
                this["ARCH_PENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_3DNOW {
            get {
                return ((bool)(this["ARCH_3DNOW"]));
            }
            set {
                this["ARCH_3DNOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_CYRIX {
            get {
                return ((bool)(this["ARCH_CYRIX"]));
            }
            set {
                this["ARCH_CYRIX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_CYRIXM {
            get {
                return ((bool)(this["ARCH_CYRIXM"]));
            }
            set {
                this["ARCH_CYRIXM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_VMX {
            get {
                return ((bool)(this["ARCH_VMX"]));
            }
            set {
                this["ARCH_VMX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RTM {
            get {
                return ((bool)(this["ARCH_RTM"]));
            }
            set {
                this["ARCH_RTM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_MPX {
            get {
                return ((bool)(this["ARCH_MPX"]));
            }
            set {
                this["ARCH_MPX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SHA {
            get {
                return ((bool)(this["ARCH_SHA"]));
            }
            set {
                this["ARCH_SHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BND {
            get {
                return ((bool)(this["ARCH_BND"]));
            }
            set {
                this["ARCH_BND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SignatureHelp_On {
            get {
                return ((bool)(this["SignatureHelp_On"]));
            }
            set {
                this["SignatureHelp_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_ADX {
            get {
                return ((bool)(this["ARCH_ADX"]));
            }
            set {
                this["ARCH_ADX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_F16C {
            get {
                return ((bool)(this["ARCH_F16C"]));
            }
            set {
                this["ARCH_F16C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_FSGSBASE {
            get {
                return ((bool)(this["ARCH_FSGSBASE"]));
            }
            set {
                this["ARCH_FSGSBASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_HLE {
            get {
                return ((bool)(this["ARCH_HLE"]));
            }
            set {
                this["ARCH_HLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_INVPCID {
            get {
                return ((bool)(this["ARCH_INVPCID"]));
            }
            set {
                this["ARCH_INVPCID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_PCLMULQDQ {
            get {
                return ((bool)(this["ARCH_PCLMULQDQ"]));
            }
            set {
                this["ARCH_PCLMULQDQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_LZCNT {
            get {
                return ((bool)(this["ARCH_LZCNT"]));
            }
            set {
                this["ARCH_LZCNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_PREFETCHWT1 {
            get {
                return ((bool)(this["ARCH_PREFETCHWT1"]));
            }
            set {
                this["ARCH_PREFETCHWT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_PRFCHW {
            get {
                return ((bool)(this["ARCH_PRFCHW"]));
            }
            set {
                this["ARCH_PRFCHW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDPID {
            get {
                return ((bool)(this["ARCH_RDPID"]));
            }
            set {
                this["ARCH_RDPID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDRAND {
            get {
                return ((bool)(this["ARCH_RDRAND"]));
            }
            set {
                this["ARCH_RDRAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDSEED {
            get {
                return ((bool)(this["ARCH_RDSEED"]));
            }
            set {
                this["ARCH_RDSEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_XSAVEOPT {
            get {
                return ((bool)(this["ARCH_XSAVEOPT"]));
            }
            set {
                this["ARCH_XSAVEOPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_UNDOC {
            get {
                return ((bool)(this["ARCH_UNDOC"]));
            }
            set {
                this["ARCH_UNDOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AES {
            get {
                return ((bool)(this["ARCH_AES"]));
            }
            set {
                this["ARCH_AES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Show_Undefined_Includes {
            get {
                return ((bool)(this["IntelliSense_Show_Undefined_Includes"]));
            }
            set {
                this["IntelliSense_Show_Undefined_Includes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color KeywordHighlighting_BorderColor {
            get {
                return ((global::System.Drawing.Color)(this["KeywordHighlighting_BorderColor"]));
            }
            set {
                this["KeywordHighlighting_BorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_SandyBridge_On {
            get {
                return ((bool)(this["PerformanceInfo_SandyBridge_On"]));
            }
            set {
                this["PerformanceInfo_SandyBridge_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_IvyBridge_On {
            get {
                return ((bool)(this["PerformanceInfo_IvyBridge_On"]));
            }
            set {
                this["PerformanceInfo_IvyBridge_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_Haswell_On {
            get {
                return ((bool)(this["PerformanceInfo_Haswell_On"]));
            }
            set {
                this["PerformanceInfo_Haswell_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_Broadwell_On {
            get {
                return ((bool)(this["PerformanceInfo_Broadwell_On"]));
            }
            set {
                this["PerformanceInfo_Broadwell_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PerformanceInfo_Skylake_On {
            get {
                return ((bool)(this["PerformanceInfo_Skylake_On"]));
            }
            set {
                this["PerformanceInfo_Skylake_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PerformanceInfo_KnightsLanding_On {
            get {
                return ((bool)(this["PerformanceInfo_KnightsLanding_On"]));
            }
            set {
                this["PerformanceInfo_KnightsLanding_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeywordHighlighting_BorderColor_On {
            get {
                return ((bool)(this["KeywordHighlighting_BorderColor_On"]));
            }
            set {
                this["KeywordHighlighting_BorderColor_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_On {
            get {
                return ((bool)(this["AsmSim_On"]));
            }
            set {
                this["AsmSim_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Show_Syntax_Errors {
            get {
                return ((bool)(this["AsmSim_Show_Syntax_Errors"]));
            }
            set {
                this["AsmSim_Show_Syntax_Errors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Decorate_Syntax_Errors {
            get {
                return ((bool)(this["AsmSim_Decorate_Syntax_Errors"]));
            }
            set {
                this["AsmSim_Decorate_Syntax_Errors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Show_Usage_Of_Undefined {
            get {
                return ((bool)(this["AsmSim_Show_Usage_Of_Undefined"]));
            }
            set {
                this["AsmSim_Show_Usage_Of_Undefined"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Decorate_Usage_Of_Undefined {
            get {
                return ((bool)(this["AsmSim_Decorate_Usage_Of_Undefined"]));
            }
            set {
                this["AsmSim_Decorate_Usage_Of_Undefined"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Decorate_Registers {
            get {
                return ((bool)(this["AsmSim_Decorate_Registers"]));
            }
            set {
                this["AsmSim_Decorate_Registers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Use_In_Code_Completion {
            get {
                return ((bool)(this["AsmSim_Use_In_Code_Completion"]));
            }
            set {
                this["AsmSim_Use_In_Code_Completion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AsmSim_Decorate_Unimplemented {
            get {
                return ((bool)(this["AsmSim_Decorate_Unimplemented"]));
            }
            set {
                this["AsmSim_Decorate_Unimplemented"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSense_Decorate_Undefined_Includes {
            get {
                return ((bool)(this["IntelliSense_Decorate_Undefined_Includes"]));
            }
            set {
                this["IntelliSense_Decorate_Undefined_Includes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_IFMA {
            get {
                return ((bool)(this["ARCH_AVX512_IFMA"]));
            }
            set {
                this["ARCH_AVX512_IFMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VBMI {
            get {
                return ((bool)(this["ARCH_AVX512_VBMI"]));
            }
            set {
                this["ARCH_AVX512_VBMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VPOPCNTDQ {
            get {
                return ((bool)(this["ARCH_AVX512_VPOPCNTDQ"]));
            }
            set {
                this["ARCH_AVX512_VPOPCNTDQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_4VNNIW {
            get {
                return ((bool)(this["ARCH_AVX512_4VNNIW"]));
            }
            set {
                this["ARCH_AVX512_4VNNIW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_4FMAPS {
            get {
                return ((bool)(this["ARCH_AVX512_4FMAPS"]));
            }
            set {
                this["ARCH_AVX512_4FMAPS"] = value;
            }
        }
    }
}
