//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmDude {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color SyntaxHighlighting_Opcode {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Opcode"]));
            }
            set {
                this["SyntaxHighlighting_Opcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color SyntaxHighlighting_Register {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Register"]));
            }
            set {
                this["SyntaxHighlighting_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color SyntaxHighlighting_Remark {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Remark"]));
            }
            set {
                this["SyntaxHighlighting_Remark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.Drawing.Color SyntaxHighlighting_Directive {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Directive"]));
            }
            set {
                this["SyntaxHighlighting_Directive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color SyntaxHighlighting_Jump {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Jump"]));
            }
            set {
                this["SyntaxHighlighting_Jump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color SyntaxHighlighting_Label {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Label"]));
            }
            set {
                this["SyntaxHighlighting_Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chocolate")]
        public global::System.Drawing.Color SyntaxHighlighting_Constant {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Constant"]));
            }
            set {
                this["SyntaxHighlighting_Constant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color SyntaxHighlighting_Misc {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Misc"]));
            }
            set {
                this["SyntaxHighlighting_Misc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyntaxHighlighting_On {
            get {
                return ((bool)(this["SyntaxHighlighting_On"]));
            }
            set {
                this["SyntaxHighlighting_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeFolding_On {
            get {
                return ((bool)(this["CodeFolding_On"]));
            }
            set {
                this["CodeFolding_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#region")]
        public string CodeFolding_BeginTag {
            get {
                return ((string)(this["CodeFolding_BeginTag"]));
            }
            set {
                this["CodeFolding_BeginTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#endregion")]
        public string CodeFolding_EndTag {
            get {
                return ((string)(this["CodeFolding_EndTag"]));
            }
            set {
                this["CodeFolding_EndTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_On {
            get {
                return ((bool)(this["CodeCompletion_On"]));
            }
            set {
                this["CodeCompletion_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_x86 {
            get {
                return ((bool)(this["CodeCompletion_x86"]));
            }
            set {
                this["CodeCompletion_x86"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_sse {
            get {
                return ((bool)(this["CodeCompletion_sse"]));
            }
            set {
                this["CodeCompletion_sse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_sse2 {
            get {
                return ((bool)(this["CodeCompletion_sse2"]));
            }
            set {
                this["CodeCompletion_sse2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_sse3 {
            get {
                return ((bool)(this["CodeCompletion_sse3"]));
            }
            set {
                this["CodeCompletion_sse3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_ssse3 {
            get {
                return ((bool)(this["CodeCompletion_ssse3"]));
            }
            set {
                this["CodeCompletion_ssse3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_sse41 {
            get {
                return ((bool)(this["CodeCompletion_sse41"]));
            }
            set {
                this["CodeCompletion_sse41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_sse42 {
            get {
                return ((bool)(this["CodeCompletion_sse42"]));
            }
            set {
                this["CodeCompletion_sse42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.felixcloutier.com/x86/")]
        public string AsmDoc_url {
            get {
                return ((string)(this["AsmDoc_url"]));
            }
            set {
                this["AsmDoc_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsmDoc_On {
            get {
                return ((bool)(this["AsmDoc_On"]));
            }
            set {
                this["AsmDoc_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeywordHighlight_On {
            get {
                return ((bool)(this["KeywordHighlight_On"]));
            }
            set {
                this["KeywordHighlight_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color KeywordHighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["KeywordHighlightColor"]));
            }
            set {
                this["KeywordHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeFolding_IsDefaultCollapsed {
            get {
                return ((bool)(this["CodeFolding_IsDefaultCollapsed"]));
            }
            set {
                this["CodeFolding_IsDefaultCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useAssemblerMasm {
            get {
                return ((bool)(this["useAssemblerMasm"]));
            }
            set {
                this["useAssemblerMasm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useAssemblerNasm {
            get {
                return ((bool)(this["useAssemblerNasm"]));
            }
            set {
                this["useAssemblerNasm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSenseShowUndefinedLabels {
            get {
                return ((bool)(this["IntelliSenseShowUndefinedLabels"]));
            }
            set {
                this["IntelliSenseShowUndefinedLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSenseShowClashingLabels {
            get {
                return ((bool)(this["IntelliSenseShowClashingLabels"]));
            }
            set {
                this["IntelliSenseShowClashingLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSenseDecorateUndefinedLabels {
            get {
                return ((bool)(this["IntelliSenseDecorateUndefinedLabels"]));
            }
            set {
                this["IntelliSenseDecorateUndefinedLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IntelliSenseDecorateClashingLabels {
            get {
                return ((bool)(this["IntelliSenseDecorateClashingLabels"]));
            }
            set {
                this["IntelliSenseDecorateClashingLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_8086 {
            get {
                return ((bool)(this["ARCH_8086"]));
            }
            set {
                this["ARCH_8086"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_186 {
            get {
                return ((bool)(this["ARCH_186"]));
            }
            set {
                this["ARCH_186"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_286 {
            get {
                return ((bool)(this["ARCH_286"]));
            }
            set {
                this["ARCH_286"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_386 {
            get {
                return ((bool)(this["ARCH_386"]));
            }
            set {
                this["ARCH_386"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_486 {
            get {
                return ((bool)(this["ARCH_486"]));
            }
            set {
                this["ARCH_486"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_MMX {
            get {
                return ((bool)(this["ARCH_MMX"]));
            }
            set {
                this["ARCH_MMX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE {
            get {
                return ((bool)(this["ARCH_SSE"]));
            }
            set {
                this["ARCH_SSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE2 {
            get {
                return ((bool)(this["ARCH_SSE2"]));
            }
            set {
                this["ARCH_SSE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE3 {
            get {
                return ((bool)(this["ARCH_SSE3"]));
            }
            set {
                this["ARCH_SSE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSSE3 {
            get {
                return ((bool)(this["ARCH_SSSE3"]));
            }
            set {
                this["ARCH_SSSE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE41 {
            get {
                return ((bool)(this["ARCH_SSE41"]));
            }
            set {
                this["ARCH_SSE41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE42 {
            get {
                return ((bool)(this["ARCH_SSE42"]));
            }
            set {
                this["ARCH_SSE42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE4A {
            get {
                return ((bool)(this["ARCH_SSE4A"]));
            }
            set {
                this["ARCH_SSE4A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE5 {
            get {
                return ((bool)(this["ARCH_SSE5"]));
            }
            set {
                this["ARCH_SSE5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX {
            get {
                return ((bool)(this["ARCH_AVX"]));
            }
            set {
                this["ARCH_AVX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX2 {
            get {
                return ((bool)(this["ARCH_AVX2"]));
            }
            set {
                this["ARCH_AVX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512VL {
            get {
                return ((bool)(this["ARCH_AVX512VL"]));
            }
            set {
                this["ARCH_AVX512VL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512 {
            get {
                return ((bool)(this["ARCH_AVX512"]));
            }
            set {
                this["ARCH_AVX512"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512DQ {
            get {
                return ((bool)(this["ARCH_AVX512DQ"]));
            }
            set {
                this["ARCH_AVX512DQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512BW {
            get {
                return ((bool)(this["ARCH_AVX512BW"]));
            }
            set {
                this["ARCH_AVX512BW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512ER {
            get {
                return ((bool)(this["ARCH_AVX512ER"]));
            }
            set {
                this["ARCH_AVX512ER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512PF {
            get {
                return ((bool)(this["ARCH_AVX512PF"]));
            }
            set {
                this["ARCH_AVX512PF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512CD {
            get {
                return ((bool)(this["ARCH_AVX512CD"]));
            }
            set {
                this["ARCH_AVX512CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512VBMI {
            get {
                return ((bool)(this["ARCH_AVX512VBMI"]));
            }
            set {
                this["ARCH_AVX512VBMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512IFMA {
            get {
                return ((bool)(this["ARCH_AVX512IFMA"]));
            }
            set {
                this["ARCH_AVX512IFMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_X64 {
            get {
                return ((bool)(this["ARCH_X64"]));
            }
            set {
                this["ARCH_X64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BMI1 {
            get {
                return ((bool)(this["ARCH_BMI1"]));
            }
            set {
                this["ARCH_BMI1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BMI2 {
            get {
                return ((bool)(this["ARCH_BMI2"]));
            }
            set {
                this["ARCH_BMI2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_P6 {
            get {
                return ((bool)(this["ARCH_P6"]));
            }
            set {
                this["ARCH_P6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_X86_64 {
            get {
                return ((bool)(this["ARCH_X86_64"]));
            }
            set {
                this["ARCH_X86_64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_IA64 {
            get {
                return ((bool)(this["ARCH_IA64"]));
            }
            set {
                this["ARCH_IA64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FPU {
            get {
                return ((bool)(this["ARCH_FPU"]));
            }
            set {
                this["ARCH_FPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FMA {
            get {
                return ((bool)(this["ARCH_FMA"]));
            }
            set {
                this["ARCH_FMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_TBM {
            get {
                return ((bool)(this["ARCH_TBM"]));
            }
            set {
                this["ARCH_TBM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AMD {
            get {
                return ((bool)(this["ARCH_AMD"]));
            }
            set {
                this["ARCH_AMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_PRIV {
            get {
                return ((bool)(this["ARCH_PRIV"]));
            }
            set {
                this["ARCH_PRIV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_PENT {
            get {
                return ((bool)(this["ARCH_PENT"]));
            }
            set {
                this["ARCH_PENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_PENTM {
            get {
                return ((bool)(this["ARCH_PENTM"]));
            }
            set {
                this["ARCH_PENTM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_NEHALEM {
            get {
                return ((bool)(this["ARCH_NEHALEM"]));
            }
            set {
                this["ARCH_NEHALEM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_WILLAMETTE {
            get {
                return ((bool)(this["ARCH_WILLAMETTE"]));
            }
            set {
                this["ARCH_WILLAMETTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_PRESCOTT {
            get {
                return ((bool)(this["ARCH_PRESCOTT"]));
            }
            set {
                this["ARCH_PRESCOTT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_WESTMERE {
            get {
                return ((bool)(this["ARCH_WESTMERE"]));
            }
            set {
                this["ARCH_WESTMERE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SANDYBRIDGE {
            get {
                return ((bool)(this["ARCH_SANDYBRIDGE"]));
            }
            set {
                this["ARCH_SANDYBRIDGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_KATMAI {
            get {
                return ((bool)(this["ARCH_KATMAI"]));
            }
            set {
                this["ARCH_KATMAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FUTURE {
            get {
                return ((bool)(this["ARCH_FUTURE"]));
            }
            set {
                this["ARCH_FUTURE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_OPT {
            get {
                return ((bool)(this["ARCH_OPT"]));
            }
            set {
                this["ARCH_OPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_NOHLE {
            get {
                return ((bool)(this["ARCH_NOHLE"]));
            }
            set {
                this["ARCH_NOHLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_3DNOW {
            get {
                return ((bool)(this["ARCH_3DNOW"]));
            }
            set {
                this["ARCH_3DNOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_PROT {
            get {
                return ((bool)(this["ARCH_PROT"]));
            }
            set {
                this["ARCH_PROT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_CYRIX {
            get {
                return ((bool)(this["ARCH_CYRIX"]));
            }
            set {
                this["ARCH_CYRIX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_INVPCID {
            get {
                return ((bool)(this["ARCH_INVPCID"]));
            }
            set {
                this["ARCH_INVPCID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_CYRIXM {
            get {
                return ((bool)(this["ARCH_CYRIXM"]));
            }
            set {
                this["ARCH_CYRIXM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_VMX {
            get {
                return ((bool)(this["ARCH_VMX"]));
            }
            set {
                this["ARCH_VMX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RTM {
            get {
                return ((bool)(this["ARCH_RTM"]));
            }
            set {
                this["ARCH_RTM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_HLE {
            get {
                return ((bool)(this["ARCH_HLE"]));
            }
            set {
                this["ARCH_HLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_MPX {
            get {
                return ((bool)(this["ARCH_MPX"]));
            }
            set {
                this["ARCH_MPX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_MIB {
            get {
                return ((bool)(this["ARCH_MIB"]));
            }
            set {
                this["ARCH_MIB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SHA {
            get {
                return ((bool)(this["ARCH_SHA"]));
            }
            set {
                this["ARCH_SHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SO {
            get {
                return ((bool)(this["ARCH_SO"]));
            }
            set {
                this["ARCH_SO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SW {
            get {
                return ((bool)(this["ARCH_SW"]));
            }
            set {
                this["ARCH_SW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SD {
            get {
                return ((bool)(this["ARCH_SD"]));
            }
            set {
                this["ARCH_SD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SX {
            get {
                return ((bool)(this["ARCH_SX"]));
            }
            set {
                this["ARCH_SX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SY {
            get {
                return ((bool)(this["ARCH_SY"]));
            }
            set {
                this["ARCH_SY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_ND {
            get {
                return ((bool)(this["ARCH_ND"]));
            }
            set {
                this["ARCH_ND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_LONG {
            get {
                return ((bool)(this["ARCH_LONG"]));
            }
            set {
                this["ARCH_LONG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_NOLONG {
            get {
                return ((bool)(this["ARCH_NOLONG"]));
            }
            set {
                this["ARCH_NOLONG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SIZE {
            get {
                return ((bool)(this["ARCH_SIZE"]));
            }
            set {
                this["ARCH_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_LOCK {
            get {
                return ((bool)(this["ARCH_LOCK"]));
            }
            set {
                this["ARCH_LOCK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_BND {
            get {
                return ((bool)(this["ARCH_BND"]));
            }
            set {
                this["ARCH_BND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_UNDOC {
            get {
                return ((bool)(this["ARCH_UNDOC"]));
            }
            set {
                this["ARCH_UNDOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_PREFETCHWT1 {
            get {
                return ((bool)(this["ARCH_PREFETCHWT1"]));
            }
            set {
                this["ARCH_PREFETCHWT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AR0 {
            get {
                return ((bool)(this["ARCH_AR0"]));
            }
            set {
                this["ARCH_AR0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AR1 {
            get {
                return ((bool)(this["ARCH_AR1"]));
            }
            set {
                this["ARCH_AR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SignatureHelp_On {
            get {
                return ((bool)(this["SignatureHelp_On"]));
            }
            set {
                this["SignatureHelp_On"] = value;
            }
        }
    }
}
