// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.166
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AsmDude
{
    static class Vsix
    {
        public const string Id = "c729d6b2-f412-49ed-893d-a8f61f25db98";
        public const string Name = "AsmDude";
        public const string Description = "Syntax highlighting and code assistance for assembly source code (.asm, .cod, .inc, .s) and the Disassembly Window ";
        public const string Language = "en-US";
        public const string Version = "1.9.6.11";
        public const string Author = "Henk-Jan Lebbink";
        public const string Tags = "Assembly, Assembler, ASM, Syntax Highlighting, Code Completion, Disassembly Window, Code Analysis, x86_64, SSE, AVX, AVX2, AVX512";
    }
}
