<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ApplicationIcon />
    <StartupObject />
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
    <LangVersion>14</LangVersion>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\asm-tools-lib\asm-tools-lib.csproj" />
  </ItemGroup>

</Project>
