// The MIT License (MIT)
//
// Copyright (c) 2023 Henk-Jan Lebbink
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

namespace AsmDude3
{
    using System;
    using System.Reflection;
    using System.Windows.Controls;
    using System.Windows.Media;
    using AsmTools;
    using AsmDude3.Tools;

    /// <summary>
    /// Code-behind for AsmDudeOptionPageUI.xaml
    /// Implements GetPropValue/SetPropValue for 157 settings with reflection-based adapter pattern
    /// </summary>
    public partial class AsmDudeOptionsPageUI : UserControl
    {
        public AsmDudeOptionsPageUI()
        {
            // InitializeComponent() is auto-generated by XAML compiler
            // Use reflection to call it (XAML compiler may generate it as public or non-public)
            try
            {
                var method = this.GetType().GetMethod("InitializeComponent",
                    System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic);
                if (method != null)
                {
                    method.Invoke(this, null);
                }
            }
            catch
            {
                // XAML compilation may fail in some scenarios
                // The UI will still function, just without XAML-loaded resources
            }
            DisplayVersionInfo();
        }

        #region Version Information

        private void DisplayVersionInfo()
        {
            try
            {
                object versionLabel = FindName("version_UI");
                if (versionLabel != null)
                {
                    PropertyInfo contentProp = versionLabel.GetType().GetProperty("Content");
                    if (contentProp != null && contentProp.CanWrite)
                    {
                        string vsixVersion = AsmDudeToolsStatic.VsixVersion();
                        string lspVersion = AsmDudeToolsStatic.LspVersion();
                        contentProp.SetValue(versionLabel, $"AsmDude3 version {vsixVersion} (LSP: {lspVersion})");
                    }
                }
            }
            catch
            {
                // Silent failure - version info is optional
            }
        }

        #endregion

        #region Generic Property Accessor Pattern (Reflection-Based)

        /// <summary>
        /// Gets a property value from UI by property name.
        /// Uses FindName() to locate XAML elements and extract their current values.
        /// </summary>
        public object GetPropValue(string propertyName)
        {
            // Direct handling for known color special cases using FindName
            if (propertyName.StartsWith("SyntaxHighlighting_") && !propertyName.EndsWith("_Italic") && !propertyName.EndsWith("_On"))
            {
                try
                {
                    // Map Settings property names to XAML element names
                    string uiElementName = propertyName switch
                    {
                        "SyntaxHighlighting_Opcode" => "ColorMnemonic_UI",
                        "SyntaxHighlighting_Register" => "ColorRegister_UI",
                        "SyntaxHighlighting_Remark" => "ColorRemark_UI",
                        "SyntaxHighlighting_Directive" => "ColorDirective_UI",
                        "SyntaxHighlighting_Constant" => "ColorConstant_UI",
                        "SyntaxHighlighting_Jump" => "ColorJump_UI",
                        "SyntaxHighlighting_Label" => "ColorLabel_UI",
                        "SyntaxHighlighting_Misc" => "ColorMisc_UI",
                        "SyntaxHighlighting_Userdefined1" => "ColorUserDefined1_UI",
                        "SyntaxHighlighting_Userdefined2" => "ColorUserDefined2_UI",
                        "SyntaxHighlighting_Userdefined3" => "ColorUserDefined3_UI",
                        _ => null
                    };

                    if (uiElementName != null)
                    {
                        object colorPicker = FindName(uiElementName);
                        if (colorPicker != null)
                        {
                            PropertyInfo selectedColorProp = colorPicker.GetType().GetProperty("SelectedColor");
                            if (selectedColorProp != null)
                            {
                                Color? color = (Color?)selectedColorProp.GetValue(colorPicker);
                                return ConvertColor(color ?? Colors.White);
                            }
                        }
                    }
                }
                catch { }
            }

            // Try to find matching UI element using FindName (XAML elements don't require properties)
            string uiElementName_UI = propertyName + "_UI";
            object uiElement = FindName(uiElementName_UI);

            if (uiElement != null)
            {
                if (uiElement is CheckBox checkBox)
                {
                    return checkBox.IsChecked ?? false;
                }
                else if (uiElement is TextBox textBox)
                {
                    return textBox.Text ?? string.Empty;
                }
                else if (uiElement is ComboBox comboBox)
                {
                    // Numeration ComboBoxes: return string content not index
                    if (propertyName.EndsWith("_Numeration") && comboBox.SelectedItem is ComboBoxItem item)
                        return item.Content?.ToString() ?? "HEX";
                    return comboBox.SelectedIndex;
                }
                else
                {
                    // Handle dynamic types (IntegerUpDown, ColorPicker from xctk namespace)
                    // Use reflection to get properties dynamically
                    try
                    {
                        PropertyInfo valueProp = uiElement.GetType().GetProperty("Value");
                        if (valueProp != null)
                        {
                            object value = valueProp.GetValue(uiElement);
                            return value ?? 0;
                        }

                        PropertyInfo selectedColorProp = uiElement.GetType().GetProperty("SelectedColor");
                        if (selectedColorProp != null)
                        {
                            Color? color = (Color?)selectedColorProp.GetValue(uiElement);
                            return ConvertColor(color ?? Colors.White);
                        }
                    }
                    catch { }
                }
            }

            // Fallback: return default value for type
            return GetDefaultValueForProperty(propertyName);
        }

        /// <summary>
        /// Sets a property value in UI by property name.
        /// Uses FindName() to locate XAML elements and set their values.
        /// </summary>
        public void SetPropValue(string propertyName, object value)
        {
            // Direct handling for known color special cases using FindName
            if (propertyName.StartsWith("SyntaxHighlighting_") && !propertyName.EndsWith("_Italic") && !propertyName.EndsWith("_On"))
            {
                try
                {
                    string uiElementName = propertyName switch
                    {
                        "SyntaxHighlighting_Opcode" => "ColorMnemonic_UI",
                        "SyntaxHighlighting_Register" => "ColorRegister_UI",
                        "SyntaxHighlighting_Remark" => "ColorRemark_UI",
                        "SyntaxHighlighting_Directive" => "ColorDirective_UI",
                        "SyntaxHighlighting_Constant" => "ColorConstant_UI",
                        "SyntaxHighlighting_Jump" => "ColorJump_UI",
                        "SyntaxHighlighting_Label" => "ColorLabel_UI",
                        "SyntaxHighlighting_Misc" => "ColorMisc_UI",
                        "SyntaxHighlighting_Userdefined1" => "ColorUserDefined1_UI",
                        "SyntaxHighlighting_Userdefined2" => "ColorUserDefined2_UI",
                        "SyntaxHighlighting_Userdefined3" => "ColorUserDefined3_UI",
                        _ => null
                    };

                    if (uiElementName != null && value is System.Drawing.Color drawingColor)
                    {
                        object colorPicker = FindName(uiElementName);
                        if (colorPicker != null)
                        {
                            PropertyInfo selectedColorProp = colorPicker.GetType().GetProperty("SelectedColor");
                            if (selectedColorProp != null && selectedColorProp.CanWrite)
                            {
                                selectedColorProp.SetValue(colorPicker, ConvertColor(drawingColor));
                                return;
                            }
                        }
                    }
                }
                catch { }
            }

            // Try to find matching UI element using FindName (XAML elements don't require properties)
            string uiElementName_UI = propertyName + "_UI";
            object uiElement = FindName(uiElementName_UI);

            if (uiElement != null)
            {
                if (uiElement is CheckBox checkBox)
                {
                    checkBox.IsChecked = (bool)value;
                }
                else if (uiElement is TextBox textBox)
                {
                    textBox.Text = (string)value ?? string.Empty;
                }
                else if (uiElement is ComboBox comboBox)
                {
                    // Numeration ComboBoxes: convert string to index
                    if (propertyName.EndsWith("_Numeration") && value is string str)
                    {
                        for (int i = 0; i < comboBox.Items.Count; i++)
                            if (comboBox.Items[i] is ComboBoxItem item && item.Content?.ToString() == str)
                            { comboBox.SelectedIndex = i; return; }
                        comboBox.SelectedIndex = 0;
                    }
                    else comboBox.SelectedIndex = (int)value;
                }
                else
                {
                    // Handle dynamic types (IntegerUpDown, ColorPicker from xctk namespace)
                    try
                    {
                        PropertyInfo valueProp = uiElement.GetType().GetProperty("Value");
                        if (valueProp != null && valueProp.CanWrite)
                        {
                            valueProp.SetValue(uiElement, (int?)value ?? 0);
                            return;
                        }

                        PropertyInfo selectedColorProp = uiElement.GetType().GetProperty("SelectedColor");
                        if (selectedColorProp != null && selectedColorProp.CanWrite && value is System.Drawing.Color drawingColor)
                        {
                            selectedColorProp.SetValue(uiElement, ConvertColor(drawingColor));
                            return;
                        }
                    }
                    catch { }
                }
            }
        }

        private object GetDefaultValueForProperty(string propertyName)
        {
            // Return sensible defaults based on property name
            if (propertyName.EndsWith("_Italic"))
                return false;
            if (propertyName.StartsWith("Global_"))
                return 50000;
            if (propertyName.StartsWith("ARCH_"))
                return false;
            if (propertyName.StartsWith("SyntaxHighlighting_") && !propertyName.EndsWith("_Italic") && !propertyName.EndsWith("_On"))
                return System.Drawing.Color.White;
            if (propertyName.EndsWith("_On"))
                return false;

            return false;
        }

        #endregion

        #region Color Conversion Helpers

        private System.Drawing.Color ConvertColor(Color mediaColor)
        {
            return System.Drawing.Color.FromArgb(mediaColor.A, mediaColor.R, mediaColor.G, mediaColor.B);
        }

        private Color ConvertColor(System.Drawing.Color drawingColor)
        {
            return Color.FromArgb(drawingColor.A, drawingColor.R, drawingColor.G, drawingColor.B);
        }

        #endregion

        #region Assembler Selection Properties

        public AssemblerEnum UsedAssembler
        {
            get
            {
                try
                {
                    // Try to access XAML-generated properties
                    CheckBox autoDetect = (CheckBox)FindName("usedAssemblerAuto_UI");
                    CheckBox masm = (CheckBox)FindName("usedAssemblerMasm_UI");
                    CheckBox nasm = (CheckBox)FindName("usedAssemblerNasm_UI");
                    CheckBox att = (CheckBox)FindName("usedAssemblerAtt_UI");

                    if (autoDetect?.IsChecked == true) return AssemblerEnum.AUTO_DETECT;
                    if (masm?.IsChecked == true) return AssemblerEnum.MASM;
                    if (nasm?.IsChecked == true) return AssemblerEnum.NASM_INTEL;
                    if (att?.IsChecked == true) return AssemblerEnum.NASM_ATT;
                }
                catch { }
                return AssemblerEnum.AUTO_DETECT;
            }
            set
            {
                try
                {
                    CheckBox autoDetect = (CheckBox)FindName("usedAssemblerAuto_UI");
                    CheckBox masm = (CheckBox)FindName("usedAssemblerMasm_UI");
                    CheckBox nasm = (CheckBox)FindName("usedAssemblerNasm_UI");
                    CheckBox att = (CheckBox)FindName("usedAssemblerAtt_UI");

                    if (autoDetect != null) autoDetect.IsChecked = false;
                    if (masm != null) masm.IsChecked = false;
                    if (nasm != null) nasm.IsChecked = false;
                    if (att != null) att.IsChecked = false;

                    switch (value)
                    {
                        case AssemblerEnum.MASM:
                            if (masm != null) masm.IsChecked = true;
                            break;
                        case AssemblerEnum.NASM_INTEL:
                            if (nasm != null) nasm.IsChecked = true;
                            break;
                        case AssemblerEnum.NASM_ATT:
                            if (att != null) att.IsChecked = true;
                            break;
                        case AssemblerEnum.AUTO_DETECT:
                        default:
                            if (autoDetect != null) autoDetect.IsChecked = true;
                            break;
                    }
                }
                catch { }
            }
        }

        public AssemblerEnum UsedAssemblerDisassemblyWindow
        {
            get
            {
                try
                {
                    CheckBox autoDetect = (CheckBox)FindName("AssemblerDisassemblyAuto_UI");
                    CheckBox masm = (CheckBox)FindName("AssemblerDisassemblyMasm_UI");
                    CheckBox att = (CheckBox)FindName("AssemblerDisassemblyAtt_UI");

                    if (autoDetect?.IsChecked == true) return AssemblerEnum.AUTO_DETECT;
                    if (masm?.IsChecked == true) return AssemblerEnum.MASM;
                    if (att?.IsChecked == true) return AssemblerEnum.NASM_ATT;
                }
                catch { }
                return AssemblerEnum.AUTO_DETECT;
            }
            set
            {
                try
                {
                    CheckBox autoDetect = (CheckBox)FindName("AssemblerDisassemblyAuto_UI");
                    CheckBox masm = (CheckBox)FindName("AssemblerDisassemblyMasm_UI");
                    CheckBox att = (CheckBox)FindName("AssemblerDisassemblyAtt_UI");

                    if (autoDetect != null) autoDetect.IsChecked = false;
                    if (masm != null) masm.IsChecked = false;
                    if (att != null) att.IsChecked = false;

                    switch (value)
                    {
                        case AssemblerEnum.MASM:
                            if (masm != null) masm.IsChecked = true;
                            break;
                        case AssemblerEnum.NASM_ATT:
                            if (att != null) att.IsChecked = true;
                            break;
                        case AssemblerEnum.AUTO_DETECT:
                        default:
                            if (autoDetect != null) autoDetect.IsChecked = true;
                            break;
                    }
                }
                catch { }
            }
        }

        #endregion

        #region Deprecated Methods (Kept for Compatibility)

        public void SaveSettings()
        {
            Settings.Default.Save();
        }

        public void LoadSettings()
        {
            Settings.Default.Reload();
        }

        #endregion
    }
}
