<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows;net48</TargetFrameworks>
    <RootNamespace>AsmTools</RootNamespace>
    <ImplicitUsings Condition="'$(TargetFramework)' != 'net48'">enable</ImplicitUsings>
    <Nullable Condition="'$(TargetFramework)' != 'net48'">enable</Nullable>
    <NoWarn>CS1668</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <!-- Using prerelease to match Microsoft.CodeAnalysis.LanguageServer.Protocol version in asm-dude2-ls-lib -->
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.6.0-2.26151.2" />
  </ItemGroup>

</Project>
