<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>AsmTools</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>CS1668</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <!-- Using prerelease to match Microsoft.CodeAnalysis.LanguageServer.Protocol version in asm-dude2-ls-lib -->
    <!-- Used by ExpressionEvaluator.cs -->
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.6.0-2.26151.2" />
  </ItemGroup>

</Project>
